logging:
  level:
    root: INFO
    ru.plants: DEBUG
  file:
    name: ${LOG_PATH:/tmp/plants-care.log}

spring:
  application:
    name: @project.artifactId@
  jpa:
    show-sql: true
    properties:
      temp:
#        use_jdbc_metadata_defaults: false
      hibernate:
      ddl-auto: none
#      ddl-auto: <create | create-drop | update | validate | none>
      format_sql: true
      generate_statistics: false
      dialect: org.hibernate.dialect.PostgreSQLDialect
      boot:
        allow_jdbc_metadata_access:false
    generate-ddl: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=plants_care_back}
    hikari:
      username: ${DB_USER:postgres}
      password: ${DB_PASS:ada5cpp}
  jackson:
    serialization:
      write_dates_as_timestamps: false

